name: secvault
description: "Application de coffre-fort numérique multi-utilisateur"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  firebase_auth: ^5.5.3
  flutter_svg: ^2.1.0
  cloud_firestore: ^5.6.8
  intl: ^0.18.0
  firebase_storage: ^12.4.6

dev_dependencies:
  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito:
  bloc_test:
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_ham.jpeg